name: jokerge
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  api_cache_manager: ^1.0.1
  http: ^1.2.2
  logger: ^2.4.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  image_path: "assets/icons/app.ico"
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
